### ISSUE TITLE
Usage example with Model classes

### ISSUE THREAD

**Issue by madflow** [amphp/postgres#6]
Hi there!

In a non-amp context I am used to have `Model` classes for the database access.  I can get the examples to work - but I have a hard time mapping the "amp" way to a model class approach.

So simple something like this:

```PHP
$dsn = 'postgres://amp:amp@localhost:1234/amp';

Amp\Loop::run(function () use ($dsn) {
    $pool = Postgres\pool($dsn);
    $model = new SomeModel($pool);
    var_dump($model->fetchAll());
   // Array of values
});
```

```PHP
class SomeModel
{
    protected $pool;

    public function __construct(Pool $pool)
    {
        $this->pool = $pool;
    }
    
    public function fetchAll()
    {
    }
}
```
Is there a another prefered way of doing this in an amp context?

Is there maybe an example project where this library is used in a "real world" application? 

Thanks!

**Comment by kelunik** [comment]
I guess what you're looking for is a library that automatically maps the data to objects? I guess there's no such library on top of Amp, yet.

There's an (abandoned) project we used to work on that's still based on Amp v1. However, it might give you some hints. Instead of returning arrays there, you could just return objects. See [here](https://github.com/bugcache/bugcache/blob/86eccd72cad9e41c65d2884d5598a8d018abd95a/src/Storage/Mysql/UserRepository.php) and [here](https://github.com/bugcache/bugcache/blob/86eccd72cad9e41c65d2884d5598a8d018abd95a/src/Storage/Mysql/AuthenticationRepository.php). `resolve` + private method there would likely be written as `Amp\call` + inline closure in Amp v2.

Hope this helps!

**Comment by madflow** [comment]
This actually does help, expecially with the examples in the old project! I used the Amp\call + inline suggestion and made some good progress. 

Closing...

**Comment by kelunik** [comment]
You're welcome. :-)
